### ISSUE TITLE
Turn this into a foreign data wrapper

### ISSUE THREAD

**Issue by davidfetter** [billrobertson42/derby2pg#1]
People might find it handy to be able to query live data in Derby.  What you have here is some large part of the way to a foreign data wrapper.

https://wiki.postgresql.org/wiki/Foreign_data_wrappers

**Comment by billrobertson42** [comment]
Thanks for the suggestion!

I thought about it briefly, but in the end, I needed a way to migrate from one database to another, and I decided to share it in case others want to do the same in the future. 

I wouldn't be opposed to writing an FDW in the future, but that's another project for another day.

**Comment by davidfetter** [comment]
Thanks for considering it!
