### ISSUE TITLE
What actuall version Derby must be?

### ISSUE THREAD

**Issue by Roland4444** [billrobertson42/derby2pg#2]
Caused by: ERROR XSLAN: Database at /home/romanx/db/testdb has an incompatible format with the current version of the software.  The database was created by or upgraded by version 10.15.

**Comment by billrobertson42** [comment]
I can’t check at the moment, but if you look into the project.clj file you can see. 

If you want to update the version and rebuild, then just install leiningen, change the version number in project file and rebuild with the command: “lein uberjar”

Let me know if you have issues.

**Comment by billrobertson42** [comment]
@Roland4444 Did you have any luck getting it to work?

**Comment by billrobertson42** [comment]
The downloadable jar has been updated to latest version of Derby.
